# Generated by Django 5.2 on 2025-06-16 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_subscriptiontype_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resume_credits',
            field=models.PositiveIntegerField(default=0, help_text='Number of resume credits available for the user.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='auth_user.subscriptiontype'),
        ),
    ]
