# Generated by Django 5.2 on 2025-06-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_paystackhook_order_usercards_pgrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgrequest',
            name='currency',
            field=models.CharField(default='NGN', help_text='Currency code for the transaction, e.g., NGN for Nigerian Naira.', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
