# Generated by Django 5.2 on 2025-06-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_pgrequest_currency_alter_subscriptiontype_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchedresumedata',
            name='auth_user_m_user_id_e79b65_idx',
        ),
        migrations.RemoveField(
            model_name='matchedresumedata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='matchedresumedata',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='matchedresumedata',
            name='txn_ref',
        ),
        migrations.AddField(
            model_name='matchedresumedata',
            name='job_title',
            field=models.CharField(default='Job Title', help_text='Title of the job for which the resume was matched.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='matchedresumedata',
            index=models.Index(fields=['user', 'job_title'], name='auth_user_m_user_id_3e2cb9_idx'),
        ),
    ]
