# Generated by Django 5.2 on 2025-06-20 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_remove_matchedresumedata_auth_user_m_user_id_e79b65_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription associated with this order, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='auth_user.subscription'),
        ),
    ]
