# Generated by Django 5.2 on 2025-06-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_order_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_renewed',
            field=models.BooleanField(default=False, help_text='Indicates if the subscription is renewed or not.'),
        ),
    ]
