# Generated by Django 5.2 on 2025-06-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_subscription_is_renewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='how_you_heard',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SOCIAL', 'Social Media'), ('ORGANIC', 'Organic'), ('REFERRAL', 'Referral'), ('BLOG', 'Blog/Content'), ('AD', 'Paid Ad'), ('OTHER', 'Other'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', help_text='How the user heard about the service.', max_length=20),
        ),
    ]
