# Generated by Django 5.2 on 2025-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.JSONField(null=True)),
                ('registered_users', models.IntegerField()),
                ('premium_users', models.IntegerField()),
                ('currently_online', models.IntegerField()),
            ],
        ),
    ]
