# Generated by Django 5.2 on 2025-09-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('normalized', models.CharField(db_index=True, max_length=255, unique=True)),
                ('skills', models.JSONField(default=list)),
                ('responsibilities', models.JSONField(default=list)),
                ('source', models.CharField(default='curated', max_length=50)),
                ('ai_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized'], name='api_jobtitl_normali_f599f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobTitleAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('action', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='api.jobtitle')),
            ],
        ),
    ]
