# Generated by Django 5.2 on 2025-09-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobtitle_jobtitleaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='jobtitle',
            name='api_jobtitl_normali_f599f1_idx',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='ai_version',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='normalized',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='source',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='field_group',
            field=models.CharField(choices=[('Technology & Engineering', 'Technology & Engineering'), ('Creative & Design', 'Creative & Design'), ('Business & Finance', 'Business & Finance'), ('Healthcare & Medical', 'Healthcare & Medical'), ('Education & Training', 'Education & Training'), ('Legal & Government', 'Legal & Government'), ('Science & Research', 'Science & Research'), ('Sales & Marketing', 'Sales & Marketing'), ('Skilled Trades & Technical Services', 'Skilled Trades & Technical Services'), ('Media & Communications', 'Media & Communications'), ('Hospitality & Tourism', 'Hospitality & Tourism'), ('Transportation & Logistics', 'Transportation & Logistics'), ('Construction & Real Estate', 'Construction & Real Estate'), ('Agriculture & Environment', 'Agriculture & Environment'), ('Human Resources & Administration', 'Human Resources & Administration'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='responsibilities',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='api.responsibility'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='api.skill'),
        ),
    ]
