# Generated by Django 5.2 on 2025-09-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_responsibility_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='field_group',
            field=models.CharField(choices=[('Technology & Engineering', 'Technology & Engineering'), ('Creative & Design', 'Creative & Design'), ('Business & Finance', 'Business & Finance'), ('Healthcare & Medical', 'Healthcare & Medical'), ('Education & Training', 'Education & Training'), ('Legal & Government', 'Legal & Government'), ('Science & Research', 'Science & Research'), ('Sales & Marketing', 'Sales & Marketing'), ('Skilled Trades & Technical Services', 'Skilled Trades & Technical Services'), ('Media & Communications', 'Media & Communications'), ('Hospitality & Tourism', 'Hospitality & Tourism'), ('Transportation & Logistics', 'Transportation & Logistics'), ('Construction & Real Estate', 'Construction & Real Estate'), ('Agriculture & Environment', 'Agriculture & Environment'), ('Human Resources & Administration', 'Human Resources & Administration'), ('Security & Protective Services', 'Security & Protective Services'), ('Social & Community Services', 'Social & Community Services'), ('Retail & Customer Service', 'Retail & Customer Service'), ('Arts, Culture & Entertainment', 'Arts, Culture & Entertainment'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
