# Generated by Django 5.2 on 2026-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_country_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
