# Generated by Django 5.2 on 2026-09-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_state_capital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='category',
        ),
        migrations.AlterField(
            model_name='technology',
            name='related_technologies',
            field=models.ManyToManyField(blank=True, to='api.technology'),
        ),
    ]
