# Generated by Django 5.2 on 2026-09-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_application_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='abbr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
