# Generated by Django 5.2 on 2026-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_degree_abbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='field_of_study',
        ),
        migrations.AddField(
            model_name='degree',
            name='fields_of_study',
            field=models.ManyToManyField(related_name='degrees', to='api.fieldofstudy'),
        ),
    ]
