# Generated by Django 5.2 on 2026-09-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_degree_field_of_study_degree_fields_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencedescription',
            name='job_title',
        ),
        migrations.AddField(
            model_name='experiencedescription',
            name='job_titles',
            field=models.ManyToManyField(related_name='experience_descriptions', to='api.jobtitle'),
        ),
    ]
