# Generated by Django 5.2 on 2026-09-13 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_serviceapikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceapikey',
            old_name='key',
            new_name='key_hash',
        ),
    ]
