# Generated by Django 5.2 on 2026-08-31 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTBAdvertisedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=10)),
                ('waist_size', models.FloatField(blank=True, null=True)),
                ('other_size', models.CharField(blank=True, max_length=32, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('image_url', models.URLField()),
                ('advertised_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('RESERVED', 'Reserved'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTBCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTBCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTBDeliveryCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('INTRASTATE', 'Intrastate'), ('INTERSTATE', 'Interstate'), ('INTERNATIONAL', 'International')], max_length=20)),
                ('location_names', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTBSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('POS', 'POS'), ('OTHER', 'Other')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], max_length=12)),
                ('sale_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTBOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_method', models.CharField(choices=[('PICKUP', 'Pickup'), ('WAYBILL', 'Waybill')], default='PICKUP', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_PAYMENT', 'Awaiting_payment'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('READY_FOR_PICKUP', 'Ready_for_pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='smtb.smtbcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='SMTBOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertised_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='smtb.smtbadvertisedproduct')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='smtb.smtborder')),
            ],
        ),
        migrations.CreateModel(
            name='SMTBRestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier', models.CharField(max_length=100)),
                ('date_received', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restocks', to='smtb.smtbcategory')),
            ],
        ),
        migrations.AddField(
            model_name='smtbadvertisedproduct',
            name='restock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertised_products', to='smtb.smtbrestock'),
        ),
        migrations.CreateModel(
            name='SMTBSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertised_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='smtb.smtbadvertisedproduct')),
                ('restock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='smtb.smtbrestock')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='smtb.smtbsale')),
            ],
        ),
    ]
