# Generated by Django 5.2 on 2026-09-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtbdeliverycharges',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smtbdeliverycharges',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='smtbdeliverycharges',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smtbsaleitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
