# Generated by Django 5.2 on 2026-09-02 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtb', '0002_smtbdeliverycharges_city_smtbdeliverycharges_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtbsale',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='smtb.smtborder'),
        ),
    ]
