# Generated by Django 5.2 on 2026-09-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smtb', '0003_smtbsale_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smtborderitem',
            old_name='sale_price',
            new_name='sales_price',
        ),
    ]
