# Generated by Django 5.2 on 2026-09-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_state_capital'),
        ('smtb', '0004_rename_sale_price_smtborderitem_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtborder',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smtb_orders', to='api.city'),
        ),
        migrations.AddField(
            model_name='smtborder',
            name='delivery_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smtb_orders', to='api.country'),
        ),
        migrations.AddField(
            model_name='smtborder',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smtb_orders', to='api.location'),
        ),
        migrations.AddField(
            model_name='smtborder',
            name='delivery_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smtb_orders', to='api.state'),
        ),
        migrations.AddField(
            model_name='smtborder',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('INTRASTATE', 'Intrastate'), ('INTERSTATE', 'Interstate'), ('INTERNATIONAL', 'International')], max_length=20, null=True),
        ),
    ]
