# Generated by Django 5.2 on 2025-10-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_webhookevent_message_webhookevent_sender_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='media_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
