# Generated by Django 5.2 on 2025-10-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_webhookevent_caption_webhookevent_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
