# Generated by Django 5.2 on 2025-10-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_webhookevent_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='customers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
