# Generated by Django 5.2 on 2025-11-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_tenant_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='fb_page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ig_business_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tg_bot_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
