# Generated by Django 5.2 on 2025-11-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_tenant_fb_page_id_tenant_ig_business_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
