# Generated by Django 5.2 on 2025-11-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_tenant_custom_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='custom_prompt',
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_prompts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
