# Generated by Django 5.2 on 2025-11-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_remove_tenant_custom_prompt_tenant_custom_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='content_schedule_times',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
