# Generated by Django 5.2 on 2025-11-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_tenant_content_schedule_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='evergreen_content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tenant',
            name='media_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
