# Generated by Django 5.2 on 2025-11-08 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_tenant_evergreen_content_tenant_media_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('subscribed', models.BooleanField(default=False)),
                ('subscription_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.tenant')),
            ],
        ),
    ]
