# Generated by Django 5.2 on 2025-12-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_automatedclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedclients',
            name='business_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
