# Generated by Django 5.2 on 2025-12-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_automatedclients_business_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedclients',
            name='content_schedule_times',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedclients',
            name='custom_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedclients',
            name='evergreen_content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='automatedclients',
            name='media_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
