# Generated by Django 5.2 on 2025-12-14 12:38

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_automatedclients_content_schedule_times_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=256)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('step', models.CharField(choices=[('code_request', 'Code Request'), ('short_lived_token', 'Short Lived Token'), ('long_lived_token', 'Long Lived Token'), ('page_token', 'Page Token')], default='initiated', max_length=50)),
                ('step_status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('code', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('short_lived_token_payload', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('long_lived_token_payload', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('page_access_token_payload', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='automatedclients',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_clients', to='automation.tenant'),
        ),
        migrations.AddField(
            model_name='automatedclients',
            name='auth_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automated_client', to='automation.facebookauthlog'),
        ),
    ]
