# Generated by Django 5.2 on 2025-12-14 15:45

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_facebookauthlog_alter_automatedclients_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedclients',
            name='access_token',
        ),
        migrations.AddField(
            model_name='automatedclients',
            name='page_access_token',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
