# Generated by Django 5.2 on 2025-12-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0015_remove_automatedclients_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedclients',
            name='saved_content',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
