# Generated by Django 5.2 on 2025-12-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_automatedclients_saved_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedclients',
            name='secret_questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
