# Generated by Django 5.2 on 2025-12-31 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_automatedclients_secret_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_count', models.IntegerField()),
                ('last_image_posted_at', models.DateTimeField()),
                ('video_count', models.IntegerField()),
                ('last_video_posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_post_log', to='automation.automatedclients')),
            ],
        ),
    ]
