# Generated by Django 5.2 on 2026-01-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0018_mediapostlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedclients',
            name='custom_prompt',
        ),
        migrations.AddField(
            model_name='automatedclients',
            name='custom_prompts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedclients',
            name='subscription_type',
            field=models.CharField(choices=[('txt', 'TXT'), ('txt-img', 'TXT-IMG'), ('txt-img-vid', 'TXT-IMG-VID')], default='txt', max_length=50),
        ),
    ]
