# Generated by Django 5.2 on 2026-01-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_remove_automatedclients_custom_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedclients',
            name='business_assets',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
