# Generated by Django 5.2 on 2026-01-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_automatedclients_business_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedclients',
            name='default_video_plans',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='automatedclients',
            name='saved_video_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
