# Generated by Django 5.2 on 2026-01-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0021_automatedclients_default_video_plans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedclients',
            name='video_plan_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
