# Generated by Django 5.2 on 2026-09-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0022_automatedclients_video_plan_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedclients',
            name='auth_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automated_client', to='automation.facebookauthlog'),
        ),
    ]
